name: Terraform apply
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Which environment to apply in
        default: staging
        required: true
        options:
          - staging
          - prod
      project:
        type: string
        description: Terraform sub-project to apply in
        required: true
      targets:
        type: string
        description: Resource identifiers to target, comma separated
permissions:
  id-token: write
  contents: read
jobs:
  apply:
    name: Apply terraform
    runs-on: ubuntu-24.04
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-north-1
          role-to-assume: arn:aws:iam::891459268445:role/TerraformMonorepoInfraCIRole
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.9.6"
      - uses: dopplerhq/cli-action@v2
      - run: doppler setup --no-interactive
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PROD_SERVICE_TOKEN }}
      - name: Configure and apply terraform
        run: |
          TARGETS=""
          IFS="," read -ra TARGET_LIST <<< "${{ github.event.inputs.targets }}"
          for target in "${TARGET_LIST[@]}"; do
            TARGETS="$TARGETS -target $(echo $target | xargs)"
          done
          pushd "${{ github.event.inputs.environment }}/${{ github.event.inputs.project }}"
            doppler run -- terraform init
            doppler run -- terraform apply -auto-approve $TARGETS
          popd
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PROD_SERVICE_TOKEN }}
